---
title: "Lezione 1: Cos'è R"
output: learnr::tutorial
runtime: shiny_prerendered
---
    
    ```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


## Rispondete alle seguenti domande per valutare i progressi fatti

```{r quiz}
quiz(
    question("Il termine R si riferisce a:",
             answer("Ad un linguaggio di programmazione"),
             answer("Ad un software"),
             answer("Ad un linguaggio di programmazione e ad un software", correct = TRUE),
             answer("Ad un grande mistero universale"),
             random_answer_order = TRUE
    ),
    question("R permette di: (più di una risposta potrebbe essere corretta)",
             answer("Eseguire analisi statistiche", correct = TRUE),
             answer("Creare applicazioni", correct = TRUE),
             answer("Creare siti web", correct = TRUE),
             answer("Scrivere libri", correct = TRUE),
             answer("Creare presentazioni in Powerpoint", correct = TRUE),
             random_answer_order = TRUE
    ),
     question("Che cos'è Bioconductor?",
             answer("Un conduttore biologico"),
             answer("Un software"),
             answer("Strumenti per analisi di dati biologicie", correct = TRUE),
             answer("Un gruppo per biologi nerd"),
             random_answer_order = TRUE
    )
)
```

