---
title: "Lezione 2: Manipolazione dei dati"
output: learnr::tutorial
runtime: shiny_prerendered
---
    
    ```{r setup, include=FALSE}
library(learnr)
library(palmerpenguins)
library(tidyverse)
```

## Select


```{r df1-setup, echo=FALSE}
penguins <- palmerpenguins::penguins

```

```{r df1, exercise=TRUE}
# Usando la tibble chiamata penguins seleziona le colonne 1, 5, 8
# Usa la funziona select e il pipe opetator %>%

penguins %>% 
    select(___, ___, ___)
```

```{r df1-hint-1}
# Sostituisci i numeri ai trattini
```

```{r df1-hint-2}
# La soluzione è
penguins %>% 
    select(1, 5, 8)
```


```{r df2, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins seleziona le colonne species, sex and year
# Usa la funziona select e il pipe opetator %>%

penguins %>% 
    select(___, ___, ___)
```

```{r df2-hint-1}
# Sostituisci i nomi delle colonne ai trattini
```

```{r df2-hint-2}
# La soluzione è
penguins %>% 
    select(species, sex, year)
```

```{r df3, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins seleziona tutte le colonne il cui nome inizia con la lettera "b".    
# Usa la funziona select e il pipe opetator %>%

penguins
```

```{r df3-hint-1}
# Utilizare la funzione help chiamata starts_with()
```

```{r df3-hint-2}
# Ricordarsi di quotare (mettere tra vircolette) la parola di interesse nella funzione starts_with()

# Es: select(starts_with("bill"))
```

```{r df3-hint-3}
# La soluzione è
penguins %>% 
    select(starts_with("b"))
```

```{r df4, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins elimina tutte le colonne il cui nome finisce con la "mm".    
# Usa la funziona select e il pipe opetator %>%

penguins
```

```{r df4-hint-1}
# Utilizare la funzione help chiamata ends_with()
```

```{r df4-hint-2}
# Ricordarsi di quotare (mettere tra vircolette) la parola di interesse nella funzione ends_with()

# Es: select(ends_with("bill"))
```

```{r df4-hint-3}
# Ricordarsi di aggiungere un meno (-) davanti alla funzione ends_with per eliminare le colonne

# Es: select(-ends_with("bill"))
```

```{r df4-hint-4}
# La soluzione è
penguins %>% 
    select(-ends_with("mm"))
```

## Filter

```{r df5, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins estrai tutte le osservazioni che contengono la specie Adelie
# Usa la funziona filter e il pipe opetator %>%

penguins
```

```{r df5-hint-1}
# Utilizare la funzione filter sulla colonna species
```

```{r df5-hint-2}
# La colonna species contenere Adelie. Per tradurlo in linguaggio R, puoi scrivere 
# species == "Adelie"

```

```{r df5-hint-3}
# La soluzione è
penguins %>% 
    filter(species == "Adelie")
```

```{r df6, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins estrai tutte le osservazioni che contengono la specie Adelie e
# e l'isola Torgersen
# Usa la funziona filter e il pipe opetator %>%

penguins
```

```{r df6-hint-1}
# Utilizare la funzione filter sulle colonne species e island
```

```{r df6-hint-2}
# La soluzione è
penguins %>% 
    filter(species == "Adelie",
           island == "Torgersen")
```

```{r df7, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins estrai tutti i pinguini dell'isola di Biscoe che hanno la lunghezza del becco
# compresa tra 34 e 36 inclusi

penguins
```

```{r df7-hint-1}
# Utilizare la funzione filter sulle colonne island e bill_length_mm
```

```{r df7-hint-2}
# La soluzione è
penguins %>% 
    filter(island == "Biscoe",
           bill_length_mm >= 34,
           bill_length_mm <= 36)
```

```{r df8, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins estrai tutti i pinguini dell'isola di Dream che hanno la lunghezza delle pinne
# minore di 179 e maggiore di 209

penguins
```

```{r df8-hint-1}
# Utilizare la funzione filter sulle colonne island e flipper_length_mm
```

```{r df8-hint-2}
# L'operatore boolean OR viene indicato nel codice da una barra verticale ( | )
# Esso deve essere usato quando volete estrarre valori più piccoli di x OR più grandi di x
```

```{r df8-hint-3}
# La soluzione è
penguins %>% 
    filter(island == "Dream",
           flipper_length_mm < 179 | flipper_length_mm > 209)
```

```{r df9, exercise=TRUE, exercise.setup = "df1-setup" }
# Usando la tibble chiamata penguins estrai  il pinguino maschio e il pinguino femmina con il 
# minore body/mass index

penguins
```

```{r df9-hint-1}
# Utilizare la funzione filter sulle colonne island e flipper_length_mm
```

```{r df9-hint-2}
# L'operatore boolean OR viene indicato nel codice da una barra verticale ( | )
# Esso deve essere usato quando volete estrarre valori più piccoli di x OR più grandi di x
```

```{r df9-hint-3}
# La soluzione è
penguins %>% 
    filter(sex == "male") %>%
    filter(body_mass_g == min(body_mass_g))
```
